Repository aritra-tech/Data-Structure-Algorithm, pull requests merged in 2022-07, with the labels that each got.

#15 Reversal_of_linked_list
  src/Data_Structure/Linked_List/Singly_Linked_List/Problems/Reverse_Linked_List.cpp
Labels: HSOC22-Level-1

#18 PreOrderTraversal
  PreOrderTraversal.cpp
Labels: HSOC22-Level-1

#22 Solution of fibonacci number in java with readme file
  src/Algorithm/Recursion/Fibonacci_number/Fibonacci_number.java
  src/Algorithm/Recursion/Fibonacci_number/README.md
Labels: PR: reviewed-approved

#27 stack ds using array in cpp added
  src/Data_Structure/Stack/Basic_Operations/stackUsingArray.cpp
Labels: PR: reviewed-approved

#29 Tree
  src/Data_Structure/Tree/Binary_Search_Tree/BinaryTree.java
Labels: PR: reviewed-approved

#30 Swap Nodes in Pairs (Done)
  .idea/misc.xml
  src/Algorithm/Recursion/SwapNodesInPairs/README.md
  src/Algorithm/Recursion/SwapNodesInPairs/SwapNodesInPairs.java
Labels: HSOC22-Level-2, PR: unreviewed

#36 Adding AVL Tree code in Tree folder
  src/Data_Structure/Tree/AVL Tree/AVL Tree.java
Labels: HSOC22-Level-2, PR: reviewed-approved

#39 Detect loop in linked list - C++
  src/Data_Structure/Linked_List/Problems/Detect loop - C++/Detect loop.cpp
Labels: HSOC22-Level-2, PR: reviewed-approved

#38 Added Dutch National Flag Algorithm (C++)
  src/Algorithm/Sorting/Dutch_National_Flag_Algo/Dutch_National_Flag_Algo.cpp
  src/Algorithm/Sorting/Dutch_National_Flag_Algo/README.md
Labels: HSOC22-Level-2, PR: reviewed-approved, PR: unreviewed

#42 Adding implementation of Singly and Circular Linked List in C++
  src/Data_Structure/Linked_List/Circular_Linked_List/Circular_Linked_List.cpp
  src/Data_Structure/Linked_List/Singly_Linked_List/Singly_Linked_List.cpp
Labels: HSOC22-Level-3, PR: reviewed-approved

#45 Trapping Rainwater (Done)
  .idea/misc.xml
  src/Algorithm/Arrays/TrappingRainWater/README.md
  src/Algorithm/Arrays/TrappingRainWater/TrappingRainWater.java
Labels: PR: reviewed-approved

#46 sparse table using c added
  src/Data_Structure/Sparse Table/SparseTable.c
  src/Data_Structure/Stack/Basic_Operations/Stack_using_Array/stackUsingArray.cpp
  src/Data_Structure/Stack/Basic_Operations/stackUsingArray.exe
Labels: HSOC22-Level-2, PR: reviewed-approved, PR: unreviewed

#48 bellman-ford algo using cpp added
  src/Data_Structure/Graph/Bellman-Ford Algorithm/BellmanFord.cpp
Labels: HSOC22-Level-1, PR: reviewed-approved

#49 Implemented c++ code of doubly linked list
  src/Data_Structure/Linked_List/Doubly_Linked_List/Doubly_linked_list.cpp
Labels: HSOC22-Level-2, PR: reviewed-approved

#50 Add N-Queens
  src/Algorithm/Backtracking/N-Queens.cpp
Labels: HSOC22-Level-2, PR: reviewed-approved, PR: unreviewed

#52 Priority Queue
  src/Data_Structure/Queue/Basic_operation/Queue_using_Array/PriorityQueueDemo.java
Labels: HSOC22-Level-2, PR: reviewed-approved

#54 Left and Right Views of Binary Tree | C++
  src/Data_Structure/Tree/Left_View_of_Binary_Tree/Left_View.cpp
  src/Data_Structure/Tree/Right_View_of_Binary_Tree/Right_View.cpp
Labels: PR: reviewed-approved

#55 Queue using Stack (Done)
  src/Data_Structure/Queue/Basic_operation/Queue_using_Stack/QueueUsingStack.java
  src/Data_Structure/Queue/Basic_operation/Queue_using_Stack/README.md
Labels: HSOC22-Level-1, PR: reviewed-approved

#60 Questions on LinkedList (Done)
  src/Data_Structure/Linked_List/Problems/MergeTwoLists/MergeTwoLists.java
  src/Data_Structure/Linked_List/Problems/MergeTwoLists/Readme.md
  src/Data_Structure/Linked_List/Problems/OddEvenLinkedList/OddEvenLinkedList.java
  src/Data_Structure/Linked_List/Problems/OddEvenLinkedList/Readme.md
  src/Data_Structure/Linked_List/Problems/PalindromeLinkedList/PalindromeLinkedList.java
  src/Data_Structure/Linked_List/Problems/PalindromeLinkedList/Readme.md
Labels: HSOC22-Level-3, PR: reviewed-approved, PR: unreviewed

#61 Adding BellmanFord Algorithm in java
  src/Data_Structure/Graph/Bellman-Ford Algorithm/BellmanFord.java
Labels: HSOC22-Level-1, PR: reviewed-approved, PR: unreviewed

#63 Add stack using Linked List
  src/Data_Structure/Stack/Basic_Operations/Stack_using_LL/stack_using_LL.cpp
  src/Data_Structure/Stack/Basic_Operations/Stack_using_LL/stackusingLL.java
Labels: HSOC22-Level-2, PR: reviewed-approved

#62 Cyclic sorting added
  src/Algorithm/Sorting/CyclicSort/CyclicSort.java
Labels: HSOC22-Level-1, PR: reviewed-approved, PR: unreviewed

#66 Inorder and Postorder Traversal | C++
  src/Data_Structure/Tree/Inorder_Traversal/Inorder_Traversal.cpp
  src/Data_Structure/Tree/Postorder_Traversal/Postorder_Traversal.cpp
Labels: HSOC22-Level-1, PR: reviewed-approved

#65 Convert Sorted Array to Binary Search Tree #58
  src/Data_Structure/Tree/Leetcode Problems/Sorted_array_to_bst/README.md
  src/Data_Structure/Tree/Leetcode Problems/Sorted_array_to_bst/Sorted_array_to_bst.cpp
Labels: HSOC22-Level-1, PR: reviewed-approved, PR: unreviewed

#78 Adding Array Element Deletion in C++
  src/Algorithm/Arrays/Array_Element_Deletion/Array_Element_Deletion.cpp
Labels: HSOC22-Level-1, PR: reviewed-approved

#77 Adding Array Element Insertion in C++
  src/Algorithm/Arrays/Array_Insertion/Array_Insertion.cpp
Labels: HSOC22-Level-1, PR: reviewed-approved

#80 Added C++ code for Queue using Array
  src/Data_Structure/Queue/Basic_operation/Queue_using_Array/Queue_Array.cpp
Labels: HSOC22-Level-2, PR: reviewed-approved

#81 Invert Binary Tree #79
  src/Data_Structure/Tree/Leetcode Problems/Invert_Binary_Tree/Invert_Binary_Tree.cpp
  src/Data_Structure/Tree/Leetcode Problems/Invert_Binary_Tree/README.md
  src/Data_Structure/Tree/Leetcode Problems/Sorted_array_to_bst/README.md
Labels: HSOC22-Level-1, PR: reviewed-approved

#83 add subsets problem
  src/Algorithm/Backtracking/N-Queens/N-Queens.cpp
  src/Algorithm/Backtracking/Subsets/Subsets.cpp
Labels: HSOC22-Level-2, PR: reviewed-approved

#82 Adding Recursion Leetcode Problems in C++
  src/Algorithm/Recursion/Leetcode_Problems/Add Two Numbers/Add_Two_Numbers.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Add Two Numbers/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Count Good Numbers/Count_Good_Numbers.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Count Good Numbers/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Decode String/Decode_String.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Decode String/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Merge Two Sorted Lists/Merge_Two_Sorted_Lists.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Merge Two Sorted Lists/Readme.md
Labels: HSOC22-Level-3

#93 Adding HashMap Implementation in cpp and Java
  src/Data_Structure/HashMap/HashMap.cpp
  src/Data_Structure/HashMap/HashMap.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#96 Recursion questions in C++
  src/Algorithm/Recursion/Leetcode_Problems/Combination_Sum/Combination_Sum.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Combination_Sum/README.md
  src/Algorithm/Recursion/Leetcode_Problems/Palindrome_Partitioning/Palindrome_Partitioning.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Palindrome_Partitioning/README.md
  src/Algorithm/Recursion/Leetcode_Problems/Subsets/README.md
  src/Algorithm/Recursion/Leetcode_Problems/Subsets/Subsets.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Subsets_II/README.md
  src/Algorithm/Recursion/Leetcode_Problems/Subsets_II/Subsets_II.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#98 Percentage of Letter in String #97
  src/Algorithm/String/Leetcode_Problems/Percentage_of_letter_in_a_string/Percentage_of_Letter_in_a_String.cpp
  src/Algorithm/String/Leetcode_Problems/Percentage_of_letter_in_a_string/README.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#100 Remove Palindromic Subsequences #99
  src/Algorithm/String/Leetcode_Problems/Remove_Palindromic_Subsequences/README.md
  src/Algorithm/String/Leetcode_Problems/Remove_Palindromic_Subsequences/Remove_Palindrome.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#103 Longest Common Prefix #101
  src/Algorithm/String/Leetcode_Problems/Longest_Common_Prefix/Longest_common_prefix.cpp
  src/Algorithm/String/Leetcode_Problems/Longest_Common_Prefix/README.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#112 Selection sort c/cpp
  src/Algorithm/Sorting/SelectionSort/SelectionSort.c
  src/Algorithm/Sorting/SelectionSort/SelectionSort.cpp
Labels: PR: reviewed-approved

#113 Remove Outermost Parentheses (using stack) #102
  src/Algorithm/String/Leetcode_Problems/Remove_Outermost_Parentheses/README.md
  src/Algorithm/String/Leetcode_Problems/Remove_Outermost_Parentheses/Remove_outer_parentheses.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#114 Added Heap Sort implementation in C++ and C
  src/Algorithm/Sorting/HeapSort/Heap_Sort.c
  src/Algorithm/Sorting/HeapSort/Heap_Sort.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#116 Right & Left View of BT (Done)
  .idea/misc.xml
  src/Data_Structure/Tree/Left_View_of_Binary_Tree/LeftViewBT_Java.java
  src/Data_Structure/Tree/Right_View_of_Binary_Tree/RightViewBT_Java.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#117 LCA (Done)
  src/Data_Structure/Tree/LCA/LCA_BST.java
  src/Data_Structure/Tree/LCA/LCA_BT.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#122 Bubble sort
  src/Algorithm/Sorting/BubbleSort/BubbleSort.c
  src/Algorithm/Sorting/BubbleSort/BubbleSort.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#118 Add Insertion Sort implementation in C++ and C #108
  src/Algorithm/Sorting/InsertionSort/Insertion_Sort.c
  src/Algorithm/Sorting/InsertionSort/Insertion_Sort.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#123 Added Queue using Linked List in Java
  src/Data_Structure/Queue/Basic_operation/Queue_using_LinkedList/QueueUsingLinkedList.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#126 Radix bucket sort
  src/Algorithm/Sorting/BucketSort/BucketSort.class
  src/Algorithm/Sorting/BucketSort/BucketSort.cpp
  src/Algorithm/Sorting/BucketSort/BucketSort.java
  src/Algorithm/Sorting/RadixSort/RadixSort.class
  src/Algorithm/Sorting/RadixSort/RadixSort.cpp
  src/Algorithm/Sorting/RadixSort/RadixSort.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#128 Insert into a Binary Search Tree #119
  src/Data_Structure/Tree/Leetcode Problems/Insert_Into_BST/InsertIntoBST.cpp
  src/Data_Structure/Tree/Leetcode Problems/Insert_Into_BST/README.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#129 Added Leetcode Searching Problems in C++
  src/Algorithm/Searching/Leetcode_problems/Find_peak_element/Readme.md
  src/Algorithm/Searching/Leetcode_problems/Find_peak_element/peak_element.cpp
  src/Algorithm/Searching/Leetcode_problems/First_and_last_element_in_sorted_array/Readme.md
  src/Algorithm/Searching/Leetcode_problems/First_and_last_element_in_sorted_array/first_and_last_Element_in_Sorted_Array.cpp
  src/Algorithm/Searching/Leetcode_problems/Minimum_in_rotated_sorted_array/Minimum_in_rotated_sorted_array.cpp
  src/Algorithm/Searching/Leetcode_problems/Minimum_in_rotated_sorted_array/Readme.md
  src/Algorithm/Searching/Leetcode_problems/Search_in_2D_matrix/Readme.md
  src/Algorithm/Searching/Leetcode_problems/Search_in_2D_matrix/search_in_2D_matrix.cpp
  src/Algorithm/Searching/Leetcode_problems/Search_in_rotated_sorted_array/Readme.md
  src/Algorithm/Searching/Leetcode_problems/Search_in_rotated_sorted_array/Search_in_rotated_sorted_array.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#132 Remove duplicates from sorted list #120
  src/Data_Structure/Linked_List/Problems/Remove Duplicates from Sorted List/RemoveDuplicatesFromSortedList.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#133 Remove duplicates from sorted array #121
  src/Data_Structure/Arrays/Remove Duplicates from Sorted Array/RemoveDuplicatesFromSortedArray.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#138 Peak Index in a Mountain Array #127
  src/Algorithm/Arrays/Leetcode Problems/Peak_Index_in_Mountain_Array/Peak_Index_in_Mountain_Array.cpp
  src/Algorithm/Arrays/Leetcode Problems/Peak_Index_in_Mountain_Array/README.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#141 Kth Largest Element in an Array #139
  src/Algorithm/Arrays/Leetcode Problems/Find_Kth_Largest/Find_Kth_Largest.cpp
  src/Algorithm/Arrays/Leetcode Problems/Find_Kth_Largest/README.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#142 Adding Cycle Detection of Undirected Graph through BFS in C++ and Java
  src/Data_Structure/Graph/Cycle_Detection_BFS/Undirected_Graph/Cycle_Detection.cpp
  src/Data_Structure/Graph/Cycle_Detection_BFS/Undirected_Graph/Cycle_Detection.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#146 Issue #109 Merge Sort Updated
  src/Algorithm/Sorting/MergeSort/merge_sort_c.c
  src/Algorithm/Sorting/MergeSort/merge_sort_cpp.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#145 Check Whether a Binary Tree is Symmetric #144
  src/Data_Structure/Tree/Leetcode_Problems/Symmetric_Tree/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Symmetric_Tree/Symmetric_tree.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#149 Added minimum cost spanning tree using prims and Kruskal’s algorithm.
  src/Data_Structure/Minimum_spanning_tree/mini_spanning_tree-Kruskal’salgorithm.cpp
  src/Data_Structure/Minimum_spanning_tree/mini_spanning_tree-prims'algorithm.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#151 Adding Recursion questions in Java
  src/Algorithm/Recursion/Leetcode_Problems/Add_Two_Numbers/Add_Two_Numbers.java
  src/Algorithm/Recursion/Leetcode_Problems/Count_Good_Numbers/Count_Good_Numbers.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Count_Good_Numbers/Count_Good_Numbers.java
  src/Algorithm/Recursion/Leetcode_Problems/Decode_String/Decode_String.java
  src/Algorithm/Recursion/Leetcode_Problems/Merge_Two_Sorted_Lists/Merge_Two_Sorted_Lists.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#152 Deepest Leaves Sum #143
  src/Data_Structure/Tree/Leetcode_Problems/Deepest_Leaves_Sum/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Deepest_Leaves_Sum/deepestLeavesSum.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#154 Added Queue using Linked List in C++ and C
  src/Data_Structure/Queue/Basic_operation/Queue_using_LinkedList/QueueUsingLinkedList.c
  src/Data_Structure/Queue/Basic_operation/Queue_using_LinkedList/QueueUsingLinkedList.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#161 Add Queue Questions #153
  src/Data_Structure/Queue/Leetcode Problems/Find_The_Winner/README.md
  src/Data_Structure/Queue/Leetcode Problems/Find_The_Winner/findTheWinner.cpp
  src/Data_Structure/Queue/Leetcode Problems/First_Unique_Char/README.md
  src/Data_Structure/Queue/Leetcode Problems/First_Unique_Char/firstUniqChar.cpp
  src/Data_Structure/Queue/Leetcode Problems/Number_of_Recent_Calls/README.md
  src/Data_Structure/Queue/Leetcode Problems/Number_of_Recent_Calls/RecentCounter.cpp
  src/Data_Structure/Queue/Leetcode Problems/README.md
  src/Data_Structure/Queue/Leetcode Problems/Reveal_Cards/README.md
  src/Data_Structure/Queue/Leetcode Problems/Reveal_Cards/deckRevealedIncreasing.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#164 Adding existing missing solutions in Java and C++
  src/Algorithm/Arrays/Array_Element_Deletion/Array_Element_Deletion.java
  src/Algorithm/Arrays/Array_Insertion/Array_Element_Insertion.java
  src/Algorithm/Arrays/Reverse_an_array/Reverse_Array.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#167 ADDED THE SOLUTIONS FOR THE QUESTIONS
  src/Algorithm/Arrays/Flipping_of_Image/flippingOfImage.cpp
  src/Algorithm/Arrays/Median_of_2_sorted_arrays/meadian_Of_2_Sorted_Arrays.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#166 Coin Change Problem in C++ #163
  src/Algorithm/Dynamic_Programing/Coin_Change/coinChange.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#171 Binary Tree Traversal in java #162
  src/Data_Structure/Tree/Inorder_Traversal/Inorder_bt.java
  src/Data_Structure/Tree/Postorder_Traversal/Postorder_bt.java
  src/Data_Structure/Tree/PreOrderTraversal/Preorder_bt.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#173 Adding missing Array Leetcode solutions in Java and C++
  src/Algorithm/Arrays/LeetcodeProblems/Find_Kth_Largest/Find_Kth_Largest.java
  src/Algorithm/Arrays/LeetcodeProblems/JumpGame/Jump_Game_II.cpp
  src/Algorithm/Arrays/LeetcodeProblems/JumpGame/Jump_Game_II.java
  src/Algorithm/Arrays/LeetcodeProblems/JumpGame/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/Peak_Index_in_Mountain_Array/Peak_Index_in_Mountain_Array.java
  src/Algorithm/Arrays/LeetcodeProblems/TrappingRainWater/TrappingRainWater.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#175 Validate BST in Java and C++ #169
  src/Data_Structure/Tree/Leetcode_Problems/Validate_BST/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Validate_BST/Valid_bst.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Validate_BST/validate_bst.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#178 Stack problems
  src/Data_Structure/Stack/Basic_Operations/Problems/Minimum_Element_from_Stack.cpp
  src/Data_Structure/Stack/Basic_Operations/Problems/Next_Greater_Element.cpp
  src/Data_Structure/Stack/Basic_Operations/Problems/Parenthesis_Checker.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#176 Added Queue implementation using two Stacks
  .idea/misc.xml
  src/Data_Structure/Stack/Basic_Operations/Stack_Using_Queue/CustomQueue.java
  src/Data_Structure/Stack/Basic_Operations/Stack_Using_Queue/ImpStackUsingQueue.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#179 added linked list questions issue#170
  src/Data_Structure/Linked_List/Singly_Linked_List/Problems/first_node_of_list_cycle.cpp
  src/Data_Structure/Linked_List/Singly_Linked_List/Problems/identical_lists.cpp
  src/Data_Structure/Linked_List/Singly_Linked_List/Problems/insert_in_sorted_list.cpp
Labels: PR: reviewed-approved

#183 Queue Reconstruction by Height (Greedy Approach) #172
  src/Data_Structure/Queue/Leetcode_Problems/Queue_Reconstruction_by_Height/README.md
  src/Data_Structure/Queue/Leetcode_Problems/Queue_Reconstruction_by_Height/reconstructQueue.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#182 Serach in rotated sorted array
  a.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#181 Add Array Problems
  src/Algorithm/Arrays/Best Time to Buy and Sell Stock/bestTimeToBuyStock.cpp
  src/Algorithm/Arrays/Best Time to Buy and Sell Stock/bestTimeToBuyStock.java
  src/Algorithm/Arrays/Best Time to Buy and Sell Stock/bestTimeToBuyStock.py
  src/Algorithm/Arrays/GroupAnagrams/groupAnagrams.cpp
  src/Algorithm/Arrays/GroupAnagrams/groupAnagrams.java
  src/Algorithm/Arrays/GroupAnagrams/groupAnagrams.py
  src/Algorithm/Arrays/Longest Consecutive Sequence/lcs.cpp
  src/Algorithm/Arrays/Longest Consecutive Sequence/lcs.java
  src/Algorithm/Arrays/Longest Consecutive Sequence/lcs.py
  src/Algorithm/Arrays/Merge Intervals/mergeIntervals.cpp
  src/Algorithm/Arrays/Merge Intervals/mergeIntervals.java
  src/Algorithm/Arrays/Merge Intervals/mergeIntervals.py
  src/Algorithm/Arrays/Pow(x,n)/pow.cpp
  src/Algorithm/Arrays/Pow(x,n)/pow.java
  src/Algorithm/Arrays/Pow(x,n)/pow.py
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#187 ArrayList questions
  src/Data_Structure/ArrayLists/Problems/ArrayListShuffle.java
  src/Data_Structure/ArrayLists/Problems/ArrayListtoLinkedList.java
  src/Data_Structure/ArrayLists/Problems/BinarySearch.java
  src/Data_Structure/ArrayLists/Problems/Duplicate.java
  src/Data_Structure/ArrayLists/Problems/JoinArrayList.java
Labels: PR: reviewed-approved

#186 Added Top & Bottom View of binary tree
  src/Data_Structure/Tree/Bottom_view_of_binary_tree/Bottom_view_of_binary_tree.cpp
  src/Data_Structure/Tree/Top_view_of_binary_tree/Top_view_of_binary_tree.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#190 Search for an element in an array using recursion
  src/Algorithm/Recursion/SearchingInArray.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#192 Matrix (Added)
  .idea/misc.xml
  src/Data_Structure/Matrix/SudokuSolver.java
  src/Data_Structure/Matrix/setMatrixZero.java
  src/Data_Structure/Matrix/spiralMatrix.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#196 Add problems on Linked Lists | C++
  src/Data_Structure/Linked_List/Problems/Add_Two_Numbers/Add_Two_Numbers.cpp
  src/Data_Structure/Linked_List/Problems/Add_Two_Numbers/README.md
  src/Data_Structure/Linked_List/Problems/Middle_Of_Linked_List/Middle_Of_Linked_List.cpp
  src/Data_Structure/Linked_List/Problems/Middle_Of_Linked_List/README.md
  src/Data_Structure/Linked_List/Problems/Remove_Nth_Node_From_End/README.md
  src/Data_Structure/Linked_List/Problems/Remove_Nth_Node_From_End/Remove_Nth_Node_From_End.cpp
  src/Data_Structure/Linked_List/Problems/Reverse_Nodes_In_K_Groups/README.md
  src/Data_Structure/Linked_List/Problems/Reverse_Nodes_In_K_Groups/Reverse_Nodes_In_K_Groups.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#199 Distribute Coins in Binary Tree #191
  src/Data_Structure/Tree/Leetcode_Problems/Distribute_coins_in_binary_tree/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Distribute_coins_in_binary_tree/distributeCoins.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#200 kadane's algorithm added
  src/Algorithm/Arrays/LeetcodeProblems/Kadane'sAlgorithm/Kadane.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#205 Maximum Binary Tree #185
  src/Data_Structure/Tree/Leetcode_Problems/Maximum_Binary_Tree/Maximum_BT.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Maximum_Binary_Tree/README.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#204 stock span solution
  src/Data_Structure/Stack/stock_span.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#206 Linked list questions
  src/Data_Structure/Linked_List/Problems/Find Length of Linked List/LengthofLinkedList.cpp
  src/Data_Structure/Linked_List/Problems/Middle Element/MiddleElement.cpp
  src/Data_Structure/Linked_List/Problems/Search an Element/SearchElement.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#207 reverse nodes in k groups addede
  src/Algorithm/Linked_list/Leetcode/Reverse_Nodes_in_K_group.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#209 Conatiner With most Water
  c.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#214 Bit Manipulation
  src/Data_Structure/BitManipulation/ComplementOfBaseTenInt.cpp
  src/Data_Structure/BitManipulation/NumberOfOneBit.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#212 Next permutation solution
  src/Algorithm/Arrays/LeetcodeProblems/Kadane'sAlgorithm/solution.java
  src/Algorithm/Arrays/LeetcodeProblems/NextPermutation/Solution.java
Labels: HSOC22-Level-1, HSOC22, PR: unreviewed

#215 Stack Solution
  src/Data_Structure/Stack/CelebrityProblem/CelebrityProblem.java
  src/Data_Structure/Stack/Parenthesis Checker/ParenthesisChecker.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#222 Add Array Questions[use of binary Search] #211
  first.java
  second.java
  third.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#229 Added Subset sum using recursion
  src/Algorithm/Recursion/GFG Problems/Subset Sum/Readme.md
  src/Algorithm/Recursion/GFG Problems/Subset Sum/Subset_sum.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#228 binary search added
  src/Algorithm/Searching/BinarySearch/Binary_search_c.c
  src/Algorithm/Searching/BinarySearch/Binary_search_cpp.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#227 Hard Pattern Problems
  src/Algorithm/Pattern/PatternOne.cpp
  src/Algorithm/Pattern/PatternTwo.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#226 linear search added
  src/Algorithm/Searching/LinearSearch/Linear_search_c.c
  src/Algorithm/Searching/LinearSearch/Linear_search_cpp.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#230 Number of good pairs
  f.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#232 Add more Stack Question
  src/Data_Structure/Stack/EvaluationOfPostfixExpression/PostfixExpression.java
  src/Data_Structure/Stack/ParanthesisChecker/ParenthesisChecker.java
  src/Data_Structure/Stack/ReverseStringUsingStack/ReverseStringUsingStack.java
  src/Data_Structure/Stack/celebrityProblem/CelebrityProblem.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#236 Recover Binary Search Tree (Issue #235)
  src/Data_Structure/Tree/Leetcode_Problems/Recover_BST/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Recover_BST/recoverTree.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#237 Distribute Coins in Binary Tree (java) #234
  src/Data_Structure/Tree/Leetcode_Problems/Distribute_coins_in_binary_tree/DistributeCoins.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#239 Added Views of BT
  src/Data_Structure/Tree/Leetcode_Problems/Distribute_coins_in_binary_tree/DistributeCoins.java
  src/Data_Structure/Tree/ViewofBT/Bottom_view_of_binary_tree/BottomViewOfBT.java
  src/Data_Structure/Tree/ViewofBT/Top_view_of_binary_tree/TopViewOfBT.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#238 Add More Array Problem
  src/Algorithm/Arrays/LeetcodeProblems/FourSumProblem/FourSum.java
  src/Algorithm/Arrays/LeetcodeProblems/FourSumProblem/README.md
  src/Algorithm/Arrays/LeetcodeProblems/TwoSumProblem/README.md
  src/Algorithm/Arrays/LeetcodeProblems/TwoSumProblem/TwoSum.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#241 Added HashMap Questions
  src/Data_Structure/HashMap/BasicOperation/Problems HashMap/ArrayListtoHash.java
  src/Data_Structure/HashMap/BasicOperation/Problems HashMap/Converting.java
  src/Data_Structure/HashMap/BasicOperation/Problems HashMap/LinkedtoHash.java
  src/Data_Structure/HashMap/BasicOperation/Problems HashMap/Pangram.java
  src/Data_Structure/HashMap/BasicOperation/Problems HashMap/particularkey.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#243 Added the files for backtracking problem
  src/Algorithm/Backtracking/Permutation_of_String/NewPermutation.gif
  src/Algorithm/Backtracking/Permutation_of_String/permuteString.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#244 How Many Numbers Are Smaller Than the Current Number
  aa.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#247 Added Linkedlist Problems in C++
  src/Data_Structure/Linked_List/Problems/Delete N nodes after M nodes of a linked list/Delete N nodes after M nodes of a linked list.cpp
  src/Data_Structure/Linked_List/Problems/Delete N nodes after M nodes of a linked list/Readme.md
  src/Data_Structure/Linked_List/Problems/Remove loop in linkedlist/Readme.md
  src/Data_Structure/Linked_List/Problems/Remove loop in linkedlist/Remove loop in linkedlist.cpp
  src/Data_Structure/Linked_List/Problems/Remove_middle_element_of_linkedlist/Readme.md
  src/Data_Structure/Linked_List/Problems/Remove_middle_element_of_linkedlist/Remove middle element in linkedlist.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#248 ADDED THE REQUIRED FILES
  src/Data_Structure/Matrix/diagonalMatrix.cpp
  src/Data_Structure/Matrix/lowerTriangle.cpp
  src/Data_Structure/Matrix/upperTriangle.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#252 Adding String Leetcode Solutions in Java
  src/Algorithm/String/Leetcode_Problems/Add_Binary/Add_Binary.java
  src/Algorithm/String/Leetcode_Problems/Add_Binary/Readme.md
  src/Algorithm/String/Leetcode_Problems/Percentage_of_letter_in_a_string/Percentage_of_letter.java
  src/Algorithm/String/Leetcode_Problems/Remove_Outermost_Parentheses/Remove_Outermost_Parantheses.java
  src/Algorithm/String/Leetcode_Problems/Remove_Palindromic_Subsequences/Remove_Palindrome.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#255 Binary Tree Pruning #245
  src/Data_Structure/Tree/Leetcode_Problems/Binary_tree_Pruning/Prune_BT.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Binary_tree_Pruning/README.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#253 Create README.md for strings
  src/Algorithm/String/Leetcode_Problems/README.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#258 Solution added
  src/Algorithm/Arrays/LeetcodeProblems/FindDuplicate/FindDuplicateInArray
  src/Algorithm/Arrays/LeetcodeProblems/FindDuplicate/README.md
  src/Algorithm/Arrays/LeetcodeProblems/MergeOverlapSubInterval/MergeOverlapSubInterval
  src/Algorithm/Arrays/LeetcodeProblems/MergeOverlapSubInterval/README.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#259 Added Hollow and Solid Diamond Programs
  src/Algorithm/Pattern/Hollow_Diamond.cpp
  src/Algorithm/Pattern/Solid_Diamond.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#265 Added Maximize Number of Nice Divisors
  src/Algorithm/Recursion/Leetcode_Problems/Maximize Number of Nice Divisors/Maximize Number of Nice Divisors.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#269 Dynamic Programming Problems #264
  src/Algorithm/Dynamic_Programing/Pascal's Triangle/README.md
  src/Algorithm/Dynamic_Programing/Pascal's Triangle/pascal_triangle.cpp
  src/Algorithm/Dynamic_Programing/Russian Doll Envelopes/README.md
  src/Algorithm/Dynamic_Programing/Russian Doll Envelopes/Russian Doll Envelopes.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#268 Adding Array Solutions
  .vscode/settings.json
  src/Algorithm/Arrays/LeetcodeProblems/ContainsmostWater/Container.cpp
  src/Algorithm/Arrays/LeetcodeProblems/FindDuplicate/FindDuplicate.cpp
  src/Algorithm/Arrays/LeetcodeProblems/FourSumProblem/4Sum.cpp
  src/Algorithm/Arrays/LeetcodeProblems/HowManyNumbersAreSmallerThantheCurrentNumber/HowManyNumbers.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#270 Pattern Problems Added
  src/Algorithm/Pattern/Diagonal and Sides of Rhombus or Diamond.cpp
  src/Algorithm/Pattern/Left_Right_Arrow.cpp
  src/Algorithm/Pattern/Solid_and_Hollow_Rhombus.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#272 Added Backtracking Problems
  src/Algorithm/Backtracking/N_Queens II/N Queens II.cpp
  src/Algorithm/Backtracking/N_Queens II/Readme.md
  src/Algorithm/Backtracking/Suduko_solver/Readme.md
  src/Algorithm/Backtracking/Suduko_solver/suduko_solver.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved
