Repository aritra-tech/Data-Structure-Algorithm, pull requests merged in 2022-08, with the labels that each got.

#275 Added Binary Tree Problems
  src/Data_Structure/Tree/Traversals/Construct_BT_from_Traversals/Constructing_BT.cpp
  src/Data_Structure/Tree/Traversals/Construct_BT_from_Traversals/README.md
  src/Data_Structure/Tree/Traversals/LevelOrder_Traversal/Level_Order_Traversal.cpp
  src/Data_Structure/Tree/Traversals/LevelOrder_Traversal/README.md
  src/Data_Structure/Tree/Traversals/VerticalOrder_Traversal/README.md
  src/Data_Structure/Tree/Traversals/VerticalOrder_Traversal/Vertical_Order_Traversal.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#278 Adding Array Questions in C++
  src/Algorithm/Arrays/LeetcodeProblems/Merge_Intervals/MergeOverlapSubInterval.java
  src/Algorithm/Arrays/LeetcodeProblems/Merge_Intervals/README.md
  src/Algorithm/Arrays/LeetcodeProblems/NextPermutation/NextPermutation.cpp
  src/Algorithm/Arrays/LeetcodeProblems/NextPermutation/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/NumberofGoodPairs/GoodPairs.cpp
  src/Algorithm/Arrays/LeetcodeProblems/TwoSumProblem/TwoSum.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#277 Baktracking questions in C++
  .vscode/settings.json
  src/Algorithm/Backtracking/Combination Sum/Combination_Sum.cpp
  src/Algorithm/Backtracking/Combination Sum/Readme.md
  src/Algorithm/Backtracking/Generate Parentheses/Generate_Parentheses.cpp
  src/Algorithm/Backtracking/Generate Parentheses/Readme.md
  src/Algorithm/Backtracking/Letter Combinations of a Phone Number/Letter_Combinations_of_a_Phone_Number.cpp
  src/Algorithm/Backtracking/Letter Combinations of a Phone Number/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#281 Added the files for sparse matrix under sparse table
  src/Algorithm/String/Leetcode_Problems/Count_Asterisks/count_Asterisks.cpp
  src/Algorithm/String/Leetcode_Problems/First_Letter_to_Appear_Twice/first_letter_repeated.cpp
  src/Algorithm/String/Leetcode_Problems/Valid_Palindrome/valid_palindrome.cpp
  src/Data_Structure/SparseTable/addingSparseMatrix.cpp
  src/Data_Structure/SparseTable/createSparseMatrix.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#288 Added Linkedlist problems
  src/Data_Structure/Linked_List/Problems/Intersection_of_Two_LL/Intersection of two LL.cpp
  src/Data_Structure/Linked_List/Problems/Intersection_of_Two_LL/Readme.md
  src/Data_Structure/Linked_List/Problems/Reverse Linkedlist_II/Readme.md
  src/Data_Structure/Linked_List/Problems/Reverse Linkedlist_II/Reverse Linkedlist_II.cpp
  src/Data_Structure/Linked_List/Problems/Sort a LL of 0s,1s,2s/Readme.md
  src/Data_Structure/Linked_List/Problems/Sort a LL of 0s,1s,2s/sort_ll_0s,1s,2s.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#287 Array and recursion
  src/Algorithm/Arrays/README.md
  src/Algorithm/Recursion/README.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#286 Adding String Leetcode Questions in C++
  src/Algorithm/String/Leetcode_Problems/Integer to Roman/Integer_to_Roman.cpp
  src/Algorithm/String/Leetcode_Problems/Integer to Roman/Readme.md
  src/Algorithm/String/Leetcode_Problems/Largest Number/Largest_Number.cpp
  src/Algorithm/String/Leetcode_Problems/Largest Number/Readme.md
  src/Algorithm/String/Leetcode_Problems/Roman to Integer/Readme.md
  src/Algorithm/String/Leetcode_Problems/Roman to Integer/Roman_to_Integer.cpp
  src/Algorithm/String/Leetcode_Problems/Word Break/Readme.md
  src/Algorithm/String/Leetcode_Problems/Word Break/Word_Break.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#284 Adding Queue Questions in C++
  src/Data_Structure/Queue/Leetcode_Problems/Design Circular Deque/Design_Circular_Deque.cpp
  src/Data_Structure/Queue/Leetcode_Problems/Design Circular Deque/Readme.md
  src/Data_Structure/Queue/Leetcode_Problems/Design Circular Queue/Design_Circular_Queue.cpp
  src/Data_Structure/Queue/Leetcode_Problems/Design Circular Queue/Readme.md
  src/Data_Structure/Queue/Leetcode_Problems/Maximum Sum Circular Subarray/Maximum.cpp
  src/Data_Structure/Queue/Leetcode_Problems/Maximum Sum Circular Subarray/Readme.md
  src/Data_Structure/Queue/Leetcode_Problems/Product of the Last K Numbers/Product.cpp
  src/Data_Structure/Queue/Leetcode_Problems/Product of the Last K Numbers/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#291 Reducing Dishes (DP) #283
  src/Algorithm/Dynamic_Programing/Reducing Dishes/README.md
  src/Algorithm/Dynamic_Programing/Reducing Dishes/reducing_dishes.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#294 Adding Linked List Ques in C++
  src/Data_Structure/Linked_List/Problems/Linked List Cycle/LLC.cpp
  src/Data_Structure/Linked_List/Problems/Linked List Cycle/Readme.md
  src/Data_Structure/Linked_List/Problems/Reorder List/RL.cpp
  src/Data_Structure/Linked_List/Problems/Reorder List/Readme.md
  src/Data_Structure/Linked_List/Problems/Rotate List/Readme.md
  src/Data_Structure/Linked_List/Problems/Rotate List/Rotate.cpp
  src/Data_Structure/Linked_List/Problems/Swap Nodes in Pairs/Readme.md
  src/Data_Structure/Linked_List/Problems/Swap Nodes in Pairs/SwapNodes.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#293 DP Questions in C++
  .vscode/settings.json
  src/Algorithm/Dynamic_Programing/Generate Parentheses/Generate_Parentheses.cpp
  src/Algorithm/Dynamic_Programing/Generate Parentheses/Readme.md
  src/Algorithm/Dynamic_Programing/Longest Palindromic Substring/LPS.cpp
  src/Algorithm/Dynamic_Programing/Longest Palindromic Substring/Readme.md
  src/Algorithm/Dynamic_Programing/Minimum Path Sum/MPS.cpp
  src/Algorithm/Dynamic_Programing/Minimum Path Sum/Readme.md
  src/Algorithm/Dynamic_Programing/Unique Paths/Readme.md
  src/Algorithm/Dynamic_Programing/Unique Paths/Unique_Paths.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#295 Introduction to Array files were added
  .idea/misc.xml
  .idea/runConfigurations/Introduction_to_Array.xml
  Data Structure & Algorithm.iml
  src/Data_Structure/Array/Introduction_to_Array.java
  src/Data_Structure/Array/Multi_Dimensional_Array.java
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#297 Updated & made the required changes
  src/Algorithm/String/Leetcode_Problems/Count_Asterisks/count_Asterisks.cpp
  src/Algorithm/String/Leetcode_Problems/Valid_Palindrome/valid_palindrome.cpp
  src/Algorithm/String/Leetcode_Problems/count_Asteriks/countAsteriks.cpp
  src/Algorithm/String/Leetcode_Problems/repeated_Character/repeatedCharacter.cpp
  src/Algorithm/String/Leetcode_Problems/valid_Palindrome/valid_Palindrome.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#296 Add Leetcode String Problems #292
  src/Algorithm/String/Leetcode_Problems/Defanging an IP Address/README.md
  src/Algorithm/String/Leetcode_Problems/Defanging an IP Address/defanging_ip_address.cpp
  src/Algorithm/String/Leetcode_Problems/Jewels and Stones/README.md
  src/Algorithm/String/Leetcode_Problems/Jewels and Stones/jewels_and_stones.cpp
  src/Algorithm/String/Leetcode_Problems/Word Ladder/README.md
  src/Algorithm/String/Leetcode_Problems/Word Ladder/Word_Ladder.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#302 Add problems on Greedy Algorithm | C++
  src/Algorithm/Arrays/LeetcodeProblems/MaximumNumberOfEvents/README.md
  src/Algorithm/Arrays/LeetcodeProblems/MaximumNumberOfEvents/Solution
  src/Algorithm/Arrays/LeetcodeProblems/MaximumProfitInJobScheduling/README.md
  src/Algorithm/Arrays/LeetcodeProblems/MaximumProfitInJobScheduling/Solution
  src/Algorithm/Arrays/LeetcodeProblems/MaximumUnitsOnATruck/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/MaximumUnitsOnATruck/Solution
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#306 Adding Recursion questions in C++
  src/Algorithm/Recursion/Leetcode_Problems/Fibonacci Number/FN.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Fibonacci Number/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Power of Four/Four.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Power of Four/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Power of Three/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Power of Three/Three.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Reverse String/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Reverse String/Reverse_String.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#305 Stack Ques in C++
  src/Data_Structure/Stack/Problems/Maximum Binary Tree/MBT.cpp
  src/Data_Structure/Stack/Problems/Maximum Binary Tree/Readme.md
  src/Data_Structure/Stack/Problems/Minimum Add to Make Parentheses Valid/MinimumAdd.cpp
  src/Data_Structure/Stack/Problems/Minimum Add to Make Parentheses Valid/Readme.md
  src/Data_Structure/Stack/Problems/Remove Duplicate Letters/RDL.cpp
  src/Data_Structure/Stack/Problems/Remove Duplicate Letters/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#304 Matrix Ques in C++
  src/Data_Structure/Matrix/LeetCode Problems/Diagonal Traverse/Diagonal_Traverse.cpp
  src/Data_Structure/Matrix/LeetCode Problems/Diagonal Traverse/Readme.md
  src/Data_Structure/Matrix/LeetCode Problems/Flood Fill/Flood_Fill.cpp
  src/Data_Structure/Matrix/LeetCode Problems/Flood Fill/Readme.md
  src/Data_Structure/Matrix/LeetCode Problems/Valid Sudoku/Readme.md
  src/Data_Structure/Matrix/LeetCode Problems/Valid Sudoku/Valid_Sudoku.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#307 Add Leetcode String Problems #303
  src/Algorithm/String/Leetcode_Problems/Count Items Matching Rule/README.md
  src/Algorithm/String/Leetcode_Problems/Count Items Matching Rule/count-items-matching-rule.cpp
  src/Algorithm/String/Leetcode_Problems/Shuffle String/README.md
  src/Algorithm/String/Leetcode_Problems/Shuffle String/shuffle-string.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#310 Add Leetcode String Problems #308
  src/Algorithm/String/Leetcode_Problems/goal_parser_interpretation/README.md
  src/Algorithm/String/Leetcode_Problems/goal_parser_interpretation/goal-parser-interpretation.cpp
  src/Algorithm/String/Leetcode_Problems/truncate_sentence/README.md
  src/Algorithm/String/Leetcode_Problems/truncate_sentence/truncateSentence.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#316 Add Binary Tree LeetCode Problems #309
  src/Data_Structure/Tree/Leetcode_Problems/Binary_tree_cameras/Binary tree cameras.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Binary_tree_cameras/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Univalued_tree/README.md
  src/Data_Structure/Tree/Leetcode_Problems/Univalued_tree/Univalued-Tree.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#324 Added Tree Ques in C++
  src/Data_Structure/Tree/Leetcode_Problems/Binary Tree Level Order Traversal/BTLOT.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Binary Tree Level Order Traversal/Readme.md
  src/Data_Structure/Tree/Leetcode_Problems/Unique Binary Search Trees II/Readme.md
  src/Data_Structure/Tree/Leetcode_Problems/Unique Binary Search Trees II/UBST2.cpp
  src/Data_Structure/Tree/Leetcode_Problems/Unique Binary Search Trees/Readme.md
  src/Data_Structure/Tree/Leetcode_Problems/Unique Binary Search Trees/UBST.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#323 Graph LeetCode Ques in CPP
  src/Data_Structure/Graph/Problems/Clone Graph/CloneGraph.cpp
  src/Data_Structure/Graph/Problems/Clone Graph/Readme.md
  src/Data_Structure/Graph/Problems/Course Schedule II/CourseSchedule_II.cpp
  src/Data_Structure/Graph/Problems/Course Schedule II/Readme.md
  src/Data_Structure/Graph/Problems/Course Schedule/CourseSchedule.cpp
  src/Data_Structure/Graph/Problems/Course Schedule/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#319 BitManipulation Ques in C++ Added
  src/Data_Structure/BitManipulation/Divide Two Integers/DTI.cpp
  src/Data_Structure/BitManipulation/Divide Two Integers/Readme.md
  src/Data_Structure/BitManipulation/Maximum Product of Word Lengths/Maximum.cpp
  src/Data_Structure/BitManipulation/Maximum Product of Word Lengths/Readme.md
  src/Data_Structure/BitManipulation/Subsets/Readme.md
  src/Data_Structure/BitManipulation/Subsets/Subsets.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#327 Total Hamming Distance (CPP) #315
  src/Data_Structure/BitManipulation/totalHammingDistance.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#326 Stack Question in Leetcode
  src/Data_Structure/Stack/Problems/Leetcode Stack Questions/BasicCalc.java
  src/Data_Structure/Stack/Problems/Leetcode Stack Questions/BinaryTreeInorder.java
  src/Data_Structure/Stack/Problems/Leetcode Stack Questions/BinarytoLinkedlist.java
  src/Data_Structure/Stack/Problems/Leetcode Stack Questions/ValidParenthese.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#325 Leetcode sorting questions
  src/Algorithm/Sorting/Problems in Sorting/Latesttimecatchbus.java
  src/Algorithm/Sorting/Problems in Sorting/MinDeleMakeArrayDivisible.java
  src/Algorithm/Sorting/Problems in Sorting/MinSquredDiff.java
  src/Algorithm/Sorting/Problems in Sorting/ResultantArrayRemovingAnagram.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#334 Array problem solved
  src/Data_Structure/ArrayLists/Problems/Four_sum.java
  src/Data_Structure/ArrayLists/Problems/ProductArray.java
  src/Data_Structure/ArrayLists/Problems/Rotate_image.java
  src/Data_Structure/ArrayLists/Problems/SetMatrixZeroes.java
  src/Data_Structure/ArrayLists/Problems/threee_sum.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#337 LinkedList Solution
  src/Striver_SDE_Sheet/Linked_List/DeleteNodeInLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/DeleteNodeInLinkedList/solution.java
  src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedArray/README.Md
  src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedArray/solution.java
  src/Striver_SDE_Sheet/Linked_List/MiddleOfLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/MiddleOfLinkedList/middleOfLinkedList.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#338 Added Backtracking Problem
  src/Algorithm/Backtracking/Knight's Tour.cpp
  src/Algorithm/Backtracking/Rat in a Maze.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#339 Added array ques
  src/Algorithm/Arrays/LeetcodeProblems/Chocolate Distribution/Chocolate_distribution.cpp
  src/Algorithm/Arrays/LeetcodeProblems/Chocolate Distribution/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/Find all duplicates in an array/Find all duplicate in an array.cpp
  src/Algorithm/Arrays/LeetcodeProblems/Find all duplicates in an array/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/Subarrays sum divisible by K/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/Subarrays sum divisible by K/Subarrays sum divisible by K.cpp
  src/Algorithm/Arrays/LeetcodeProblems/Subarrays sum equal K/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/Subarrays sum equal K/Subarrays sum equal K.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#342 Dp problems added
  src/Algorithm/Dynamic_Programing/Edit_Distance/edit_distance.java
  src/Algorithm/Dynamic_Programing/House_Robbers/house_robbers.java
  src/Algorithm/Dynamic_Programing/Maximum_Product_Subarray/max_prod_subarray.java
  src/Algorithm/Dynamic_Programing/Unique_Paths/Unique_Paths.java
  src/Striver_SDE_Sheet/Linked_List/MiddleOfLinkedList/LinkedList.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#345 Leetcode linked list questions
  src/Algorithm/Recursion/LeetCode Recursion Problems/Eleminationgame.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/MaximumNoofNiceDivisors.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/PowerofTwo.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/pow.java
  src/Data_Structure/Linked_List/Leetcode LinkedList Question/LinkedList.java
  src/Data_Structure/Linked_List/Leetcode LinkedList Question/MergeLists.java
  src/Data_Structure/Linked_List/Leetcode LinkedList Question/Reversekgroup.java
  src/Data_Structure/Linked_List/Leetcode LinkedList Question/Rotatelist.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#344 LeetCode Recursion questions
  src/Algorithm/Recursion/LeetCode Recursion Problems/Eleminationgame.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/MaximumNoofNiceDivisors.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/PowerofTwo.java
  src/Algorithm/Recursion/LeetCode Recursion Problems/pow.java
Labels: PR: unreviewed

#350 String Solution added
  src/Striver_SDE_Sheet/Strings/RepeatedStringMatch/README.md
  src/Striver_SDE_Sheet/Strings/RepeatedStringMatch/Solution.java
  src/Striver_SDE_Sheet/Strings/StringToInteger/README.md
  src/Striver_SDE_Sheet/Strings/StringToInteger/Solution.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#347 Added Backtracking Problems
  src/Algorithm/Backtracking/Hamiltonian Cycle.cpp
  src/Algorithm/Backtracking/Solving Cryptarithmetic Puzzles(Algorithm).cpp
  src/Algorithm/Backtracking/m Coloring.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#351 Added Pattern Problem
  src/Algorithm/Pattern/Butterfly Pattern.cpp
  src/Algorithm/Pattern/Diagonal & Sides of a Rectangle.cpp
  src/Algorithm/Pattern/Hollow Diamond Inscribed in a Rectangle.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#355 Added Searching Algorithm
  src/Algorithm/Searching/Exponential Search.cpp
  src/Algorithm/Searching/Interpolation Search.cpp
  src/Algorithm/Searching/Jump Search.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#354 Added Linkedlist Problems
  src/Data_Structure/Linked_List/Problems/Convert Binary Number in a Linked List to Integer/Convert Binary Number in a Linked List to Integer.cpp
  src/Data_Structure/Linked_List/Problems/Convert Binary Number in a Linked List to Integer/Readme.md
  src/Data_Structure/Linked_List/Problems/Delete without head pointer/Delete without head pointer.cpp
  src/Data_Structure/Linked_List/Problems/Delete without head pointer/Readme.md
  src/Data_Structure/Linked_List/Problems/Multiply two numbers represented by Linked Lists/Multiply two numbers represented by Linked Lists.cpp
  src/Data_Structure/Linked_List/Problems/Multiply two numbers represented by Linked Lists/Readme.md
  src/Data_Structure/Linked_List/Problems/Remove Linked List Elements/Readme.md
  src/Data_Structure/Linked_List/Problems/Remove Linked List Elements/Remove Linked List Elements.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#357 Added Graph Algorithm
  src/Data_Structure/Graph/Dijkstra’s shortest path algorithm/Dijkstra’s shortest path algorithm.cpp
  src/Data_Structure/Graph/Floyd Warshall Algorithm/Floyd Warshall Algorithm.cpp
  src/Data_Structure/Graph/Kruskal’s Minimum Spanning Tree Algorithm/Kruskal’s Minimum Spanning Tree Algorithm.cpp
  src/Data_Structure/Graph/Prim’s Minimum Spanning Tree (MST)/Prim’s Minimum Spanning Tree (MST).cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#360 Adding Array Questions in Java
  src/Striver_SDE_Sheet/Arrays/Best Time to Buy and Sell Stock/Best.java
  src/Striver_SDE_Sheet/Arrays/Best Time to Buy and Sell Stock/Readme.md
  src/Striver_SDE_Sheet/Arrays/Sort Colors/Readme.md
  src/Striver_SDE_Sheet/Arrays/Sort Colors/SC.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#359 Array Questions in Java
  src/Striver_SDE_Sheet/Arrays/Maximum Subarray/MS.java
  src/Striver_SDE_Sheet/Arrays/Maximum Subarray/Readme.md
  src/Striver_SDE_Sheet/Arrays/Next Permutation/NP.java
  src/Striver_SDE_Sheet/Arrays/Next Permutation/Readme.md
  src/Striver_SDE_Sheet/Arrays/Pascal's Triangle/Pascal's_Triangle.java
  src/Striver_SDE_Sheet/Arrays/Pascal's Triangle/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#366 Adding String Questions of Striver's SDE Sheet in C++
  src/Striver_SDE_Sheet/Strings/Compare Version Numbers/Compare.cpp
  src/Striver_SDE_Sheet/Strings/Compare Version Numbers/Readme.md
  src/Striver_SDE_Sheet/Strings/Count and Say/Count.cpp
  src/Striver_SDE_Sheet/Strings/Count and Say/Readme.md
  src/Striver_SDE_Sheet/Strings/Valid Anagram/Anagram.cpp
  src/Striver_SDE_Sheet/Strings/Valid Anagram/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#365 Linked List Questions of Striver SDE Sheet in C++
  src/Striver_SDE_Sheet/Linked_List/Intersection of Two Linked Lists/Intersection.cpp
  src/Striver_SDE_Sheet/Linked_List/Intersection of Two Linked Lists/Readme.md
  src/Striver_SDE_Sheet/Linked_List/Linked List Cycle II/LLCycleII.cpp
  src/Striver_SDE_Sheet/Linked_List/Linked List Cycle II/Readme.md
  src/Striver_SDE_Sheet/Linked_List/Reverse Nodes in k-Group/Readme.md
  src/Striver_SDE_Sheet/Linked_List/Reverse Nodes in k-Group/ReverseNodes.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#368 Linked List question of Striver SDE Sheet in C++
  src/Striver_SDE_Sheet/Linked_List/DeleteNodeInLinkedList/Delete.cpp
  src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedLinkedList/Merge.cpp
  src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedLinkedList/solution.java
  src/Striver_SDE_Sheet/Linked_List/MiddleOfLinkedList/Middle.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#367 Added String Questions in C++
  src/Striver_SDE_Sheet/Strings/RepeatedStringMatch/Repeated.cpp
  src/Striver_SDE_Sheet/Strings/StringToInteger/String.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#373 String Questions of Striver's SDE Sheet in Java Added
  src/Striver_SDE_Sheet/Strings/Compare Version Numbers/Compare.java
  src/Striver_SDE_Sheet/Strings/Count and Say/Count.java
  src/Striver_SDE_Sheet/Strings/Valid Anagram/Anagram.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#372 Linked List Questions of Striver's SDE Sheet in Java Added
  src/Striver_SDE_Sheet/Linked_List/Intersection of Two Linked Lists/Intersection.java
  src/Striver_SDE_Sheet/Linked_List/Linked List Cycle II/LLCycleII.java
  src/Striver_SDE_Sheet/Linked_List/Reverse Nodes in k-Group/ReverseNodes.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#378 Array Ques. (SDE SHEET)
  src/Striver_SDE_Sheet/Arrays/MajorityElement-1/Readme.md
  src/Striver_SDE_Sheet/Arrays/MajorityElement-1/solution.java
  src/Striver_SDE_Sheet/Arrays/MajorityElement-2/README.md
  src/Striver_SDE_Sheet/Arrays/MajorityElement-2/Solution.java
  src/Striver_SDE_Sheet/Arrays/UniquePathGrid/README.md
  src/Striver_SDE_Sheet/Arrays/UniquePathGrid/Solution.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#376 Queue Question in Java Added
  src/Data_Structure/Queue/Leetcode_Problems/Design_Circular_Deque/Design_Circular_Deque.java
  src/Data_Structure/Queue/Leetcode_Problems/Find_The_Winner/FindTheWinner.java
  src/Data_Structure/Queue/Leetcode_Problems/MaximumSumCircularSubarray/Maximum.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#382 DP Questions in CPP
  src/Algorithm/Dynamic_Programing/BuyandSellStocks/BuySellStocks.cpp
  src/Algorithm/Dynamic_Programing/BuyandSellStocksII/BuyandSellStocksII.cpp
  src/Algorithm/Dynamic_Programing/Climbing_Stairs/ClimbingStairs.cpp
  src/Algorithm/Dynamic_Programing/Longest_Common_Subsequence/LCS.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#381 Stack Questions in Java added
  src/Data_Structure/Stack/Problems/MaximumBinaryTree/MBT.java
  src/Data_Structure/Stack/Problems/MinimumAddtoMakeParenthesesValid/MinimumAdd.java
  src/Data_Structure/Stack/Problems/RemoveDuplicateLetters/RDL.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#386 sde linked list added
  src/Striver_SDE_Sheet/Linked_List/Add_two_numbers/AddTwoNumbers.java
  src/Striver_SDE_Sheet/Linked_List/Add_two_numbers/README.md
  src/Striver_SDE_Sheet/Linked_List/Remove_the_nth_node/README.md
  src/Striver_SDE_Sheet/Linked_List/Remove_the_nth_node/Remove_nth_node.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#385 Added Searching Algorithms
  src/Algorithm/Searching/Fibonacci Search/Fibonacci Search.cpp
  src/Algorithm/Searching/Recursive program to linearly search an element in a given array/Recursive program to linearly search an element in a given array.cpp
  src/Algorithm/Searching/Sublist Search/Sublist Search.cpp
  src/Algorithm/Searching/The Ubiquitous Binary Search/The Ubiquitous Binary Search.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#391 Added Dp problems
  src/Algorithm/Dynamic_Programing/Frog_Jump/FrogJump.cpp
  src/Algorithm/Dynamic_Programing/HouseRobberII/HouseRobberII.cpp
  src/Algorithm/Dynamic_Programing/HouseRobberII/Readme.md
  src/Algorithm/Dynamic_Programing/House_Robbers/Readme.md
  src/Algorithm/Dynamic_Programing/House_Robbers/house_robbers.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#390 Added Graph Algorithms
  src/Data_Structure/Graph/GraphAlgorithms/Bridges in a graph/Bridges in a graph.cpp
  src/Data_Structure/Graph/GraphAlgorithms/Hierholzer’s Algorithm/Hierholzer’s Algorithm.cpp
  src/Data_Structure/Graph/GraphAlgorithms/Jhonson's Algorithm/Jhonson's Algorithm.cpp
  src/Data_Structure/Graph/GraphAlgorithms/Topological Sorting/Topological Sorting.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#392 Added solutions to matrix problems
  src/Data_Structure/Matrix/LeetCodeProblems/Search in 2D matrix /README.md
  src/Data_Structure/Matrix/LeetCodeProblems/Search in 2D matrix /search_in_2D_matrix.cpp
  src/Data_Structure/Matrix/LeetCodeProblems/WordSearch/README.md
  src/Data_Structure/Matrix/LeetCodeProblems/WordSearch/wordSearch.java
  src/Data_Structure/Matrix/LeetCodeProblems/kth Weakest Row/README.md
  src/Data_Structure/Matrix/LeetCodeProblems/kth Weakest Row/kth_weakest_row_in_matrix.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#394 leetcode prob
  src/Algorithm/Arrays/LeetcodeProblems/Binary Search/Binary Search.cpp
  src/Algorithm/Arrays/LeetcodeProblems/Binary Search/Readme.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#398 Array Question in Java
  src/Algorithm/Arrays/LeetcodeProblems/Findallduplicatesinanarray/FindAllDuplicates.java
  src/Algorithm/Arrays/LeetcodeProblems/Flipping_of_Image/Flipping.java
  src/Algorithm/Arrays/LeetcodeProblems/Flipping_of_Image/Readme.md
  src/Algorithm/Arrays/LeetcodeProblems/MaximumNumberOfEvents/MaximumEvents.cpp
  src/Algorithm/Arrays/LeetcodeProblems/MaximumProfitInJobScheduling/MaximumProfit.cpp
  src/Algorithm/Arrays/LeetcodeProblems/MaximumProfitInJobScheduling/MaximumProfit.java
  src/Algorithm/Arrays/LeetcodeProblems/Median_of_2_sorted_arrays/Median_Of_2_Sorted_Arrays.cpp
  src/Algorithm/Arrays/LeetcodeProblems/Median_of_2_sorted_arrays/median_sorted_array.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#400 #393 add graph problems
  src/Data_Structure/Graph/Problems/BipartiteGraph/IsGraphBipartite.cpp
  src/Data_Structure/Graph/Problems/BipartiteGraph/Readme.md
  src/Data_Structure/Graph/Problems/FloodFill/FloodFill.cpp
  src/Data_Structure/Graph/Problems/FloodFill/Readme.md
  src/Data_Structure/Graph/Problems/MaxAreaOfIsland/MaxAreaOfIsland.cpp
  src/Data_Structure/Graph/Problems/MaxAreaOfIsland/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#399 Recursion Questions Added
  src/Algorithm/Recursion/Leetcode_Problems/EliminationGame/EliminationGame.cpp
  src/Algorithm/Recursion/Leetcode_Problems/EliminationGame/Eliminationgame.java
  src/Algorithm/Recursion/Leetcode_Problems/EliminationGame/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/MaximizeNumberofNiceDivisors/MaximizeNumberofNiceDivisors.cpp
  src/Algorithm/Recursion/Leetcode_Problems/MaximizeNumberofNiceDivisors/MaximumNoofNiceDivisors.java
  src/Algorithm/Recursion/Leetcode_Problems/MaximizeNumberofNiceDivisors/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Pow/Pow.cpp
  src/Algorithm/Recursion/Leetcode_Problems/Pow/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/Pow/pow.java
  src/Algorithm/Recursion/Leetcode_Problems/PowerofTwo/PowerofTwo.cpp
  src/Algorithm/Recursion/Leetcode_Problems/PowerofTwo/PowerofTwo.java
  src/Algorithm/Recursion/Leetcode_Problems/PowerofTwo/Readme.md
  src/Algorithm/Recursion/Leetcode_Problems/SwapNodesInPairs/SwapNodes.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#402 Backtracking Questions added
  src/Algorithm/Backtracking/CombinationSum/CombinationSum.java
  src/Algorithm/Backtracking/GenerateParentheses/GenerateParantheses.java
  src/Algorithm/Backtracking/N_Queens/NQueens.java
  src/Algorithm/Backtracking/N_Queens/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#407 Added SDE sheet string problems
  src/Striver_SDE_Sheet/Strings/LongestCommonPrefix/LongestCommonPrefix.cpp
  src/Striver_SDE_Sheet/Strings/LongestCommonPrefix/Readme.md
  src/Striver_SDE_Sheet/Strings/ReverseWordsInString/Readme.md
  src/Striver_SDE_Sheet/Strings/ReverseWordsInString/ReverseWordsInString.cpp
  src/Striver_SDE_Sheet/Strings/RomanToInteger/Readme.md
  src/Striver_SDE_Sheet/Strings/RomanToInteger/RomanToInteger.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#406 Fixes #403
  .vscode/settings.json
  src/Striver_SDE_Sheet/Linked_List/Flattening_a_Linked_List/Flattening.cpp
  src/Striver_SDE_Sheet/Linked_List/Flattening_a_Linked_List/Flattening.java
  src/Striver_SDE_Sheet/Linked_List/Flattening_a_Linked_List/Readme.md
  src/Striver_SDE_Sheet/Linked_List/Linked_List_Cycle/LinkedListCycle.cpp
  src/Striver_SDE_Sheet/Linked_List/Linked_List_Cycle/LinkedListCycle.java
  src/Striver_SDE_Sheet/Linked_List/Linked_List_Cycle/Readme.md
  src/Striver_SDE_Sheet/Linked_List/Palindrome_Linked_List/PalindromeLinkedList.cpp
  src/Striver_SDE_Sheet/Linked_List/Palindrome_Linked_List/PalindromeLinkedList.java
  src/Striver_SDE_Sheet/Linked_List/Palindrome_Linked_List/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#408 Linkedlist Solution
  src/Striver_SDE_Sheet/Linked_List/FlatteningOfLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/FlatteningOfLinkedList/solution.java
  src/Striver_SDE_Sheet/Linked_List/IntersactionOfLinkedList/IntersactionOfLinkedList.java
  src/Striver_SDE_Sheet/Linked_List/IntersactionOfLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/LinkedCycle2/README.md
  src/Striver_SDE_Sheet/Linked_List/LinkedCycle2/solution.java
  src/Striver_SDE_Sheet/Linked_List/PalindromeLinkedList/README.md
  src/Striver_SDE_Sheet/Linked_List/PalindromeLinkedList/palindrome.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#412 added the leetcode solution
  src/Data_Structure/Linked_List/Problems/Removenthnode/Readme.md
  src/Data_Structure/Linked_List/Problems/Removenthnode/Removenthnode.cpp
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#415 Stack Questions added in CPP
  src/Data_Structure/Stack/Problems/AddTwoNumbersII/AddTwoNumbersII.cpp
  src/Data_Structure/Stack/Problems/AddTwoNumbersII/Readme.md
  src/Data_Structure/Stack/Problems/BasicCalculator/BasicCalculator.cpp
  src/Data_Structure/Stack/Problems/BasicCalculator/Readme.md
  src/Data_Structure/Stack/Problems/ReorderList/Readme.md
  src/Data_Structure/Stack/Problems/ReorderList/ReorderList.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#414 Fixes #409
  src/Data_Structure/BitManipulation/ComplementofBase10Integer/Complement.java
  src/Data_Structure/BitManipulation/ComplementofBase10Integer/README.md
  src/Data_Structure/BitManipulation/DivideTwoIntegers/DTI.java
  src/Data_Structure/BitManipulation/MaximumProductofWordLengths/Maximum.java
  src/Data_Structure/BitManipulation/Numberof1Bits/Numberof1Bits.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#416 binary string duplication
  src/Data_Structure/BitManipulation/BinaryStringDuplication/BinaryStringDuplication.cpp
  src/Data_Structure/BitManipulation/BinaryStringDuplication/Readme.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#417 Stack and Queue Questions of Striver's SDE Sheet added
  src/Striver_SDE_Sheet/Stack_and_Queue/LFUCache/LFUCache.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/LFUCache/LFUCache.java
  src/Striver_SDE_Sheet/Stack_and_Queue/LFUCache/Readme.md
  src/Striver_SDE_Sheet/Stack_and_Queue/LRUCache/LRUCache.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/LRUCache/LRUCache.java
  src/Striver_SDE_Sheet/Stack_and_Queue/LRUCache/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#420 Infix to Postfix
  src/Data_Structure/Stack/Problems/Infix to Postfix/InfixtoPostfix.c
  src/Data_Structure/Stack/Problems/Infix to Postfix/Readme.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#422 Disintegrate a Doubly Linked List
  src/Data_Structure/Linked_List/Problems/Disintegrate a Doubly Linked List/Disintegrateadoubly.c
  src/Data_Structure/Linked_List/Problems/Disintegrate a Doubly Linked List/Readme.md
Labels: HSOC22-Level-1, HSOC22, PR: reviewed-approved

#426 Stack and queue SDE SHEET
  src/Striver_SDE_Sheet/Stack_and_Queue/Implement a queue/Implement a queue.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/Implement a queue/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/Implement a stack using queue/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/Implement a stack using queue/stackusingqueue.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved, SDE-Sheet

#423 String Question From SDE sheet
  src/Striver_SDE_Sheet/Strings/KMP-algo/README.md
  src/Striver_SDE_Sheet/Strings/KMP-algo/solution.java
  src/Striver_SDE_Sheet/Strings/MinimumCharactersForPalindrome/README.md
  src/Striver_SDE_Sheet/Strings/MinimumCharactersForPalindrome/solution.java
  src/Striver_SDE_Sheet/Strings/Z-algorithm/README.md
  src/Striver_SDE_Sheet/Strings/Z-algorithm/solution.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#429 Fixes #425
  src/Algorithm/Recursion/Leetcode_Problems/Add_Two_Numbers/AddTwoNumbers.java
  src/Algorithm/Recursion/Leetcode_Problems/Combination_Sum/CombinationSum.java
  src/Algorithm/Recursion/Leetcode_Problems/Decode_String/DecodeString.java
  src/Algorithm/Recursion/Leetcode_Problems/Palindrome_Partitioning/PalindromePartitioning.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#428 Array Questions in CPP Added
  src/Algorithm/Arrays/LeetcodeProblems/ProductofArrayExceptSelf/Product.cpp
  src/Algorithm/Arrays/LeetcodeProblems/RotateImage/RotateImage.cpp
  src/Algorithm/Arrays/LeetcodeProblems/SetMatrixZeroes/SetMatrixZeroes.cpp
  src/Algorithm/Arrays/LeetcodeProblems/ThreeSum/ThreeSum.cpp
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#431 Stack and Queue solution [SDE SHEET]
  src/Striver_SDE_Sheet/Stack_and_Queue/LargestRectangleInHistogram/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/LargestRectangleInHistogram/solution.java
  src/Striver_SDE_Sheet/Stack_and_Queue/MinStack/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/MinStack/solution.java
  src/Striver_SDE_Sheet/Stack_and_Queue/SlidingWindowMaximum/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/SlidingWindowMaximum/solution.java
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved, SDE-Sheet

#432 ADDED SOLUTIONS FOR LEETCODE PROBLEMS
  src/Algorithm/String/Leetcode_Problems/Implement strStr()/README.md
  src/Algorithm/String/Leetcode_Problems/Implement strStr()/strStr().cpp
  src/Data_Structure/Matrix/LeetCodeProblems/AvialableCapturesForARook/Data_Structure/Matrix/LeetCodeProblems/AvialableCapturesForARook/README.md
  src/Data_Structure/Matrix/LeetCodeProblems/AvialableCapturesForARook/Data_Structure/Matrix/LeetCodeProblems/AvialableCapturesForARook/avialableCaptures.java
  src/Data_Structure/Matrix/LeetCodeProblems/Convert1dto2d/Convert.cpp
  src/Data_Structure/Matrix/LeetCodeProblems/Convert1dto2d/README.md
  src/Data_Structure/Matrix/LeetCodeProblems/Determine  Weather matrix an  be rotated or not/IsRotated().cpp
  src/Data_Structure/Matrix/LeetCodeProblems/Determine  Weather matrix an  be rotated or not/README.md
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#434 Tiling a rectangle with fewest squares
  src/Algorithm/Backtracking/Tiling a rectangle  with fewest squares/Readme.md
  src/Algorithm/Backtracking/Tiling a rectangle  with fewest squares/Tiling.cpp
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved

#433 Added Linkedlist problems
  src/Data_Structure/Linked_List/Problems/FlatteningaLinkedList/Flattening a Linked List.cpp
  src/Data_Structure/Linked_List/Problems/FlatteningaLinkedList/Readme.md
  src/Data_Structure/Linked_List/Problems/Merge Sort for LinkedList/Merge Sort for Linked List.cpp
  src/Data_Structure/Linked_List/Problems/Merge Sort for LinkedList/Readme.md
  src/Data_Structure/Linked_List/Problems/OddEvenLinkedList/Odd Even Linked List.cpp
  src/Data_Structure/Linked_List/Problems/OddEvenLinkedList/Readme.md
  src/Data_Structure/Linked_List/Problems/PalindromeLinkedList/PalindromeLinkedList.cpp
  src/Data_Structure/Linked_List/Problems/PalindromeLinkedList/Readme.md
Labels: HSOC22-Level-3, HSOC22, PR: reviewed-approved

#435 Added Stack and Queue Problems
  src/Striver_SDE_Sheet/Stack_and_Queue/NextGreaterElement/Greater_Element.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/NextGreaterElement/Greater_Element.java
  src/Striver_SDE_Sheet/Stack_and_Queue/NextGreaterElement/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/SortStack/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/SortStack/Sort_Stack.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/SortStack/Sort_Stack.java
  src/Striver_SDE_Sheet/Stack_and_Queue/ValidParentheses/README.md
  src/Striver_SDE_Sheet/Stack_and_Queue/ValidParentheses/valid_parentheses.cpp
  src/Striver_SDE_Sheet/Stack_and_Queue/ValidParentheses/valid_parentheses.java
Labels: HSOC22-Level-2, HSOC22, PR: reviewed-approved
